# Generated by Django 5.2.10 on 2026-01-20 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_vehicle"),
        ("reservations", "0003_reservation_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="accounts.vehicle",
            ),
        ),
    ]
