# Generated by Django 5.2.10 on 2026-01-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_reservation_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="car_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
