# Generated by Django 5.1.4 on 2026-01-27 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_car_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(help_text='NicePay Transaction ID', max_length=50, unique=True)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='READY', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.reservation')),
            ],
        ),
    ]
