# Generated by Django 5.2.10 on 2026-01-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="is_driver",
            field=models.BooleanField(
                default=True, help_text="Designates whether the user is a driver."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_host",
            field=models.BooleanField(
                default=False, help_text="Designates whether the user is a host."
            ),
        ),
    ]
