# Generated by Django 5.2.10 on 2026-01-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_user_car_model_user_car_number_user_gender_user_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="car_model",
        ),
        migrations.RemoveField(
            model_name="user",
            name="car_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
