# Generated by Django 5.1.4 on 2026-01-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
