# Generated by Django 5.2.10 on 2026-01-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="spaces/"),
        ),
    ]
