# Generated by Django 5.1.4 on 2026-01-20 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_space_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='image',
        ),
        migrations.CreateModel(
            name='SpaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spaces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spaces.space')),
            ],
        ),
    ]
