# Generated by Django 5.2.10 on 2026-01-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0003_remove_space_image_spaceimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="is_auto_approval",
            field=models.BooleanField(default=True),
        ),
    ]
